kind: pipeline
name: default

steps:
- name: rubocop
  image: ruby
  commands:
  - bundle install --jobs=3 --retry=3
  - bin/bundle exec rubocop
- name: test
  image: ruby
  commands:
  - bundle install --jobs=3 --retry=3
  - bin/bundle exec rake test
