Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
  - 'config/environments/*.rb'
  - 'test/**/*.rb'
Metrics/ClassLength:
    Exclude:
    - 'test/**/*.rb'
Documentation:
  Enabled: false
AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'bin/**/*'
  - 'db/migrate/*'
  - 'vendor/**/*'
