language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.0

jobs:
  include:
    - stage: test
      script: bin/rake db:migrate RAILS_ENV=test
      script: bin/rake test
    - stage: rubocop
      script: bin/bundle exec rubocop


after_success:
  - bin/bundle exec codeclimate-test-reporter
