language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.0

jobs:
  include:
    - stage: test
      script: 
      - bin/rake db:migrate RAILS_ENV=test
      - bin/rake test
    - script: bin/bundle exec rubocop

