language: ruby

sudo: false

rvm:
  - 2.4.0

script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake test
  - bin/bundle exec rubocop
  - bin/bundle exec codeclimate-test-reporter

after_success:
  - bin/bundle exec codeclimate-test-reporter
