language: ruby
cache: bundler
sudo: false
addons:
  chrome: stable

rvm:
  - 2.4.0

jobs:
  include:
    - stage: test
      script: 
      - bin/rake db:migrate RAILS_ENV=test
      - bin/rake test
    - script: bin/bundle exec rubocop
    - script: bin/bundle exec rails_best_practices
    - script: bin/bundle exec brakeman
    - script:
      - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
      - unzip ~/chromedriver_linux64.zip -d ~/
      - rm ~/chromedriver_linux64.zip
      - sudo mv -f ~/chromedriver /usr/local/share/
      - sudo chmod +x /usr/local/share/chromedriver
      - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      - bin/bundle exec rails test:system