version: '2'
services:
  db:
    image: postgres:9.4.1
    environment:
    - POSTGRES_PASSWORD=Password123!
    - POSTGRES_USER=juno
    - POSTGRES_DB=juno_production

  redis:
    image: redis

  web:
    build: .
    ports:
      - "3000:80"
    links:
      - db
      - smtp
      - redis
      - sidekiq
    command: ./start.sh
    environment:
    - PG_ENV_POSTGRES_USER=juno
    - PG_ENV_POSTGRES_PASSWORD=Password123!
    - PG_PORT_5432_TCP_ADDR=db
    - SECRET_KEY=oiwefhoin230w0ifh203h0hfewo
    - RAILS_ENV=production
    - SITE_ADDRESS=localhost
    - REDIS_URL=redis://redis
    - JUNO_PROBE_SECRET=sda23r23fwedsfergv32r3r
    - RAILS_SERVE_STATIC_FILES=true

  sidekiq:
    build: .
    links:
      - db
      - redis
    command: bundle exec sidekiq -e production
    environment:
    - PG_ENV_POSTGRES_USER=juno
    - PG_ENV_POSTGRES_PASSWORD=Password123!
    - PG_PORT_5432_TCP_ADDR=db
    - SECRET_KEY=oiwefhoin230w0ifh203h0hfewo
    - REDIS_URL=redis://redis
    - JUNO_PROBE_SECRET=sda23r23fwedsfergv32r3r

  smtp:
    image: namshi/smtp

  juno-probe:
    image: allistera/juno-probe
    restart: on-failure
    depends_on:
      - web
    environment:
      JUNO_URL: http://web
      JUNO_PROBE_URL: http://juno-probe:9090
      JUNO_PROBE_PORT: 9090
      JUNO_PROBE_SECRET: sda23r23fwedsfergv32r3r
      JUNO_PROBE_NAME: Europe/London
