version: '2'
services:
  db:
    image: postgres:9.4.1
    environment:
    - POSTGRES_PASSWORD=Password123!
    - POSTGRES_USER=juno
    - POSTGRES_DB=juno_production

  redis:
    image: redis

  web:
    build: . 
    ports:
      - "3000:80"
    links:
      - db
      - smtp
      - redis
      - sidekiq
    volumes:
      - .:/myapp
    command: ./start.sh
    environment:
    - PG_ENV_POSTGRES_USER=juno
    - PG_ENV_POSTGRES_PASSWORD=Password123!
    - PG_PORT_5432_TCP_ADDR=db
    - SECRET_KEY=oiwefhoin230w0ifh203h0hfewo
    - RAILS_ENV=production
    - SITE_ADDRESS=localhost
    - REDIS_URL=redis://redis

  sidekiq:
    build: .
    links:
      - db
      - redis
    command: bundle exec sidekiq -e production
    environment:
    - PG_ENV_POSTGRES_USER=juno
    - PG_ENV_POSTGRES_PASSWORD=Password123!
    - PG_PORT_5432_TCP_ADDR=db
    - SECRET_KEY=oiwefhoin230w0ifh203h0hfewo
    - REDIS_URL=redis://redis

  smtp:
    image: namshi/smtp
