apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.9.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq
  name: sidekiq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sidekiq
    spec:
      containers:
      - args:
        - bundle
        - exec
        - sidekiq
        - -e
        - production
        env:
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: web-secrets
              key: sentry
        - name: JUNO_PROBE_SECRET
          valueFrom:
            secretKeyRef:
              name: probe-secrets
              key: secret
        - name: PG_ENV_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: PG_ENV_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: username
        - name: PG_PORT_5432_TCP_ADDR
          value: db
        - name: REDIS_URL
          value: redis://redis
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: web-secrets
              key: secret
        image: allistera/juno:{{ .Values.web.tag }}
        name: sidekiq
        resources: {}
      restartPolicy: Always
status: {}
